# Configuration for HCMC AI Challenge 2026 on Kaggle
data:
  # Thu muc cha chua toan bo cac video tu L21 den Lxx
  raw_dir: "/kaggle/input/datasets/quninhphmanh/ai-challenge-hcmc-2026-videos"
  
  # Thu muc cha chua toan bo cac thu muc Keyframes_L21, Keyframes_L22, ..., Keyframes_Lxx
  keyframes_dir: "/kaggle/input/datasets/quninhphmanh/ai-challenge-hcmc-2026-keyframes"
  
  # Thu muc chua toan bo cac file vector dac trung .npy
  features_dir: "/kaggle/input/datasets/quninhphmanh/ai-challenge-hcmc-2026-features/clip-features-32"
  
  # Thu muc chua cac file JSON thong tin YouTube (Media-info)
  metadata_dir: "/kaggle/input/datasets/quninhphmanh/ai-challenge-hcmc-2026-metadata/media-info-aic25-b1/media-info"
  
  # Thu muc chua cac file CSV mapping khung hinh
  map_keyframes_dir: "/kaggle/input/datasets/quninhphmanh/ai-challenge-hcmc-2026-metadata/map-keyframes-aic25-b1/map-keyframes"
  
  output_dir: "/kaggle/working/output"

models:
  clip_model: "openai/clip-vit-base-patch32"
  vlm_model: "Qwen/Qwen2-VL-2B-Instruct"


search:
  top_k_videos: 10
  top_k_frames: 100
